// Generated by CoffeeScript 1.6.2
(function() {
  var ASSETS, AimPlayerMover, BULLET_IMG, Bullet, Enemy, Material, Mover, PLAYER_IMG, Player, Shooter, StraightMover, StraightShooter, add, enemies, enemy_bullets, game, intoWindow, isInWindow, normalize, p, player, player_bullets, players, remove, to_angle, to_angle_material, to_vec,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  enchant();

  ASSETS = [PLAYER_IMG = 'player.png', BULLET_IMG = 'icon0.png'];

  game = null;

  player = null;

  players = null;

  enemies = null;

  player_bullets = null;

  enemy_bullets = null;

  Function.prototype.property = function(prop, desc) {
    return Object.defineProperty(this.prototype, prop, desc);
  };

  p = function() {
    var ret, v, _i, _len;

    ret = [];
    for (_i = 0, _len = arguments.length; _i < _len; _i++) {
      v = arguments[_i];
      console.log(v);
      ret.push(v);
    }
    if (ret.length === 1) {
      return ret[0];
    } else {
      return ret;
    }
  };

  normalize = function(x, y) {
    var len;

    len = Math.sqrt(x * x + y * y);
    return [x / len, y / len];
  };

  to_angle = function(x, y) {
    return Math.atan2(y, x) + Math.PI / 2;
  };

  to_angle_material = function(mat1, mat2) {
    return to_angle(mat2.rx - mat1.rx, mat2.ry - mat1.ry);
  };

  to_vec = function(angle) {
    return [Math.cos(angle - Math.PI / 2), Math.sin(angle - Math.PI / 2)];
  };

  add = function(node) {
    return game.currentScene.addChild(node);
  };

  remove = function(node) {
    return game.currentScene.removeChild(node);
  };

  isInWindow = function(material) {
    var _ref, _ref1;

    return (0 <= (_ref = material.rx) && _ref < game.width) && (0 <= (_ref1 = material.ry) && _ref1 < game.height);
  };

  intoWindow = function(material) {
    var t;

    if (material.rx < 0) {
      material.rx = 0;
    }
    t = game.width - 1;
    if (material.rx > t) {
      material.rx = t;
    }
    if (material.ry < 0) {
      material.ry = 0;
    }
    t = game.height - 1;
    if (material.ry > t) {
      return material.ry = t;
    }
  };

  Material = (function(_super) {
    __extends(Material, _super);

    function Material(img_name, frame, width, height, rradius, group) {
      this.rradius = rradius;
      this.group = group;
      Material.__super__.constructor.call(this, width, height);
      this.image = game.assets[img_name];
      this.frame = frame;
      this.group.addChild(this);
      this.hp = 1;
      this.power = 1;
    }

    Material.prototype.damage = function(material) {
      this.hp -= material.power;
      if (this.hp <= 0) {
        return this.hp = 0;
      }
    };

    Material.prototype.attack = function(material) {
      material.damage(this);
      return this.damage(material);
    };

    Material.property('rx', {
      get: function() {
        return this.x + this.width / 2;
      },
      set: function(x) {
        return this.x = x - this.width / 2;
      }
    });

    Material.property('ry', {
      get: function() {
        return this.y + this.height / 2;
      },
      set: function(y) {
        return this.y = y - this.height / 2;
      }
    });

    Material.prototype.ondying = function() {};

    Material.prototype.hit_check = function(material) {
      var dist, rdist;

      rdist = Math.pow(this.rx - material.rx, 2) + Math.pow(this.ry - material.ry, 2);
      dist = Math.pow(this.rradius + material.rradius, 2);
      return rdist <= dist;
    };

    return Material;

  })(Sprite);

  Player = (function(_super) {
    __extends(Player, _super);

    function Player() {
      Player.__super__.constructor.call(this, PLAYER_IMG, 27, 32, 32, 4, players);
      this.scale(2, 2);
      this.rx = game.width / 2;
      this.ry = game.height / 2;
      this.core = new Material(BULLET_IMG, 20, 16, 16, 0, game.currentScene);
      this.core.scale(this.rradius * 2 / this.core.width, this.rradius * 2 / this.core.height);
      this.core.rx = this.rx;
      this.core.ry = this.ry;
    }

    Player.prototype.onenterframe = function() {
      var i, _i, _results;

      this.core.rx = this.rx;
      this.core.ry = this.ry;
      if (game.frame % (game.fps / 10) === 0) {
        _results = [];
        for (i = _i = -2; _i <= 2; i = ++_i) {
          _results.push(new Bullet(48, this.rx + (this.width / 4) * i, this.ry - this.height / 2, 0, -10, player_bullets));
        }
        return _results;
      }
    };

    Player.prototype.ondying = function() {
      return remove(this.core);
    };

    return Player;

  })(Material);

  Enemy = (function(_super) {
    __extends(Enemy, _super);

    function Enemy(x, y) {
      Enemy.__super__.constructor.call(this, PLAYER_IMG, 27, 32, 32, 16, enemies);
      this.scale(2, -2);
      this.rx = x;
      this.ry = y;
      this.hp = 10;
      this.mover = new Mover;
      this.shooter = new Shooter;
    }

    Enemy.prototype.onenterframe = function() {
      if (game.frame % (game.fps / 5) === 0) {
        this.shooter["do"](this);
      }
      return this.mover["do"](this);
    };

    return Enemy;

  })(Material);

  Mover = (function() {
    function Mover() {}

    Mover.prototype["do"] = function() {};

    return Mover;

  })();

  StraightMover = (function(_super) {
    __extends(StraightMover, _super);

    function StraightMover(vx, vy) {
      this.vx = vx;
      this.vy = vy;
    }

    StraightMover.prototype["do"] = function(material) {
      material.rx += this.vx;
      material.ry += this.vy;
      if (!isInWindow(this)) {
        return this.hp = 0;
      }
    };

    return StraightMover;

  })(Mover);

  AimPlayerMover = (function(_super) {
    __extends(AimPlayerMover, _super);

    function AimPlayerMover(v, mat) {
      this.v = v;
      this.mat = mat != null ? mat : null;
      this.fixed_v = normalize(player.rx - this.mat.rx, player.ry - this.mat.ry);
    }

    AimPlayerMover.prototype["do"] = function(material) {
      var vx, vy, _ref;

      _ref = this.mat != null ? this.fixed_v : normalize(player.rx - material.rx, player.ry - material.ry), vx = _ref[0], vy = _ref[1];
      material.rx += vx * this.v;
      return material.ry += vy * this.v;
    };

    return AimPlayerMover;

  })(Mover);

  Shooter = (function() {
    function Shooter() {}

    Shooter.prototype["do"] = function() {};

    return Shooter;

  })();

  StraightShooter = (function(_super) {
    __extends(StraightShooter, _super);

    function StraightShooter(way, space) {
      this.way = way;
      this.space = space;
      this.px = player.rx;
      this.py = player.ry;
    }

    StraightShooter.prototype["do"] = function(material) {
      var angle, i, vx, vy, _i, _ref, _ref1, _results;

      angle = to_angle(this.px - material.rx, this.py - material.ry) + (this.way % 2 === 0 ? this.space / 2 : this.space) * Math.floor(this.way / 2);
      _results = [];
      for (i = _i = 1, _ref = this.way; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
        _ref1 = to_vec(angle).map(function(e) {
          return e * 6;
        }), vx = _ref1[0], vy = _ref1[1];
        new Bullet(56, material.rx, material.ry, vx, vy, enemy_bullets);
        _results.push(angle -= this.space);
      }
      return _results;
    };

    return StraightShooter;

  })(Shooter);

  Bullet = (function(_super) {
    __extends(Bullet, _super);

    function Bullet(frame, x, y, vx, vy, group) {
      this.vx = vx;
      this.vy = vy;
      Bullet.__super__.constructor.call(this, BULLET_IMG, frame, 16, 16, 4, group);
      this.rx = x;
      this.ry = y;
      this.rotate(to_angle(this.vx, this.vy) / Math.PI * 180);
    }

    Bullet.prototype.onenterframe = function() {
      this.rx += this.vx;
      this.ry += this.vy;
      if (!isInWindow(this)) {
        return this.hp = 0;
      }
    };

    return Bullet;

  })(Material);

  window.onload = function() {
    game = new Game(400, 600);
    game.fps = 60;
    game.preload(ASSETS);
    game.onload = function() {
      var bex, bey, scene;

      scene = game.rootScene;
      scene.backgroundColor = '#ffffff';
      players = new Group;
      add(players);
      enemies = new Group;
      add(enemies);
      player_bullets = new Group;
      add(player_bullets);
      enemy_bullets = new Group;
      add(enemy_bullets);
      player = new Player;
      scene.onenterframe = function() {
        var char_set, char_sets, e, first, m, second, set, _i, _j, _k, _l, _len, _len1, _len2, _len3, _len4, _m, _ref, _ref1, _ref2, _ref3;

        _ref = [player_bullets, enemy_bullets, players, enemies];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          set = _ref[_i];
          _ref1 = set.childNodes;
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            m = _ref1[_j];
            if ((m != null ? m.hp : void 0) <= 0) {
              m.ondying();
              m.group.removeChild(m);
            }
          }
        }
        char_sets = [[player_bullets, enemies], [enemy_bullets, players], [enemies, players]];
        for (_k = 0, _len2 = char_sets.length; _k < _len2; _k++) {
          char_set = char_sets[_k];
          _ref2 = char_set[0].childNodes;
          for (_l = 0, _len3 = _ref2.length; _l < _len3; _l++) {
            first = _ref2[_l];
            _ref3 = char_set[1].childNodes;
            for (_m = 0, _len4 = _ref3.length; _m < _len4; _m++) {
              second = _ref3[_m];
              if (first.hit_check(second)) {
                first.attack(second);
              }
            }
          }
        }
        if (game.frame % (game.fps * 1) === 0) {
          (function() {});
          e = new Enemy(0, 0);
          e.shooter = new StraightShooter(2, Math.PI / 10);
          e.mover = new AimPlayerMover(4, e);
          e = new Enemy(game.width, 0);
          e.shooter = new StraightShooter(2, Math.PI / 10);
          return e.mover = new AimPlayerMover(4, e);
        }
      };
      bex = bey = 0;
      scene.ontouchstart = function(e) {
        bex = e.x;
        return bey = e.y;
      };
      return scene.ontouchmove = function(e) {
        player.rx += e.x - bex;
        player.ry += e.y - bey;
        intoWindow(player);
        bex = e.x;
        return bey = e.y;
      };
    };
    return game.start();
  };

}).call(this);
